# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: DataSchool
email: dataschool@chartio.com
description: A community-driven school of free web books and content written by people who work with data for people who work with data.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://dataschool.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: dataschool
github_username:  chartio
slack_url: "https://join.slack.com/t/thedataschool/shared_invite/enQtNjAyMTM1MTk1MzQ4LWY4YWI1YzBkOTAwZmQ4Y2Q4N2U4MWE1Njg3OWJhNmU2NGRiYTI0MDEzMmQ1MzllMTczMGFhMTEwZTBlYmQxYjY"

sqlboxurl: "https://sqlbox.herokuapp.com/"
#sqlboxurl: "http://localhost:8084" # localhost sqlbox

# Build settings
markdown: kramdown
permalink: /:path/

collections:
  people:
    output: true
  books:
    output: true
  chapters:
    output: true

plugins:
      - jekyll-last-modified-at
      - jekyll-sitemap
      - jekyll-feed
      # - jekyll-pdf


# Set defaults for YAML Front Matter variables
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "people"
    values:
      picture: "static/uploads/people/pictures/default.jpg"
      layout: "person"
  - scope:
      path: ""
      type: "books"
    values:
      layout: "book"
      permalink: "/:path/"
      is_hidden: false
  - scope:
      path: ""
      type: "chapters"
    values:
      layout: "chapter"
      permalink: "/:path/"
      is_hidden: false
      is_featured: false
      section: "book"
  - scope:
      path: "static/"
    values:
      permalink: "/"

# set defaults per book
  - scope:
      path: "_chapters/data-governance"
      type: "chapters"
    values:
      book_slug: data-governance
      image: /assets/images/book-covers/data-governance.png  # Set to book's cover
      permalink: "/data-governance/:slug/"
  - scope:
      path: "_chapters/data-modeling-101"
      type: "chapters"
    values:
      book_slug: data-modeling-101
      image: /assets/images/book-covers/data-modeling-101.png  # Set to book's cover
      permalink: "/data-modeling-101/:slug/"
  - scope:
      path: "_chapters/fundamentals-of-analysis"
      type: "chapters"
    values:
      book_slug: fundamentals-of-analysis
      image: /assets/images/book-covers/fundamentals-of-analysis.png  # Set to book's cover
      permalink: "/fundamentals-of-analysis/:slug/"
  - scope:
      path: "_chapters/how-to-design-a-dashboard"
      type: "chapters"
    values:
      book_slug: how-to-design-a-dashboard
      image: /assets/images/book-covers/how-to-design-a-dashboard.png  # Set to book's cover
      permalink: "/how-to-design-a-dashboard/:slug/"
  - scope:
      path: "_chapters/how-to-teach-people-sql"
      type: "chapters"
    values:
      book_slug: how-to-teach-people-sql
      image: /assets/images/book-covers/how-to-teach-people-sql.png  # Set to book's cover
      permalink: "/how-to-teach-people-sql/:slug/"
  - scope:
      path: "_chapters/sql-optimization"
      type: "chapters"
    values:
      book_slug: sql-optimization
      image: /assets/images/book-covers/sql-optimization.png  # Set to book's cover
      permalink: "/sql-optimization/:slug/"
  - scope:
      path: "_chapters/misrepresenting-data"
      type: "chapters"
    values:
      book_slug: misrepresenting-data
      image: /assets/images/book-covers/misrepresenting-data.png  # Set to book's cover
      permalink: "/misrepresenting-data/:slug/"
  - scope:
      path: "_chapters/dictionary"
      type: "chapters"
    values:
      book_slug: dictionary
      image: /assets/images/book-covers/data-school-dictionary.png
      layout: dictionary
  - scope:
      path: "_chapters/data-conversations"
      type: "chapters"
    values:
      book_slug: data-conversations
      image: /assets/images/final-textbook-design.jpg
      permalink: "/data-conversations/:slug/"

  - scope:
      path: "_chapters/learn-sql"
      type: "chapters"
    values:
      book_slug: learn-sql
      database: "PostgreSQL"
      dbname: "herokuchinook"
      section: Extras
      number: 999999
      needs_sqlbox: true
      permalink: "/learn-sql/:slug/"
      image: /assets/images/book-covers/learn-sql.png  # Set to book's cover
  - scope:
      path: "downloads/"
    values:
      layout: book-full



feed:
  collections:
    chapters:
      path: "/chapters.xml"
